name: CI
on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci 
      - run: npm run format
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: build project
        if: gtihub.event_name == 'push'
        run: npm run build
      - name: deploy to staging
        if: gtihub.event_name == 'push'
        run: npx surge --project ./build --domain snobbish-secretaryyuvalberber.surge.sh 
        env:
          SURGE_LOGIN: ${{ secret.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secret.SURGE_TOKEN }}
      